server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/it-much/{application}
          uri: https://git.oschina.net/it-much/{application}
          uri: https://git.oschina.net/it-much/{application}
          uri: https://git.oschina.net/it-much/{application}
